
<UserMain>:
	name: 'UserMain'
	FloatLayout:
		orientation: 'horizontal'
		Button:
			size_hint: None, None
			size: 250, 50
			pos: root.width - self.width, root.height - self.height
			text:'Deslog'
			
			on_press:
				root.deslog()
			
		Tab:
			id: main_tab
		
			
<Tab>:
	configs:configs
	do_default_tab: False
	#tab_width: 40
	
	on_touch_down:
		self.update_user_current_screen()
	
	TabDocs:
		id:docs
			
	TabConfigs:
		id:configs
		
	TabTutorial:
		id:tutorial

	TabContact:
		id:contact
